version: '3.8'

services:
  backend:
    container_name: 'rad-det-api'
    image: 'ghcr.io/lnls-sirius/rad-det-backend:1.1.2'
    build:
      context: ./back_end
    ports:
      - 80:80
  frontend:
    container_name: 'rad-det'
    image: 'ghcr.io/lnls-sirius/rad-det-frontend:1.1.6'
    build:
      context: ./front_end
    ports:
      - 3000:80
