version: '3.8'

services:
  backend:
    container_name: 'server-rad-det'
    image: 'ghcr.io/lnls-sirius/rad-det-backend:1.0.0'
    build:
      context: ./back_end
    ports:
      - 8080:8080
  frontend:
    container_name: 'rad-det'
    image: 'ghcr.io/lnls-sirius/rad-det-frontend:1.0.0'
    build:
      context: ./front_end
    ports:
      - 3000:80
